### ISSUE TITLE
Podcast/Youtube channel text in arrow

### ISSUE THREAD

**Issue by JessWakelin** [shescoding/shescoding-dot-org#52] opened 2015-04-17 11:48 UTC
When i press on Podcasts/YouTube Channels it doesnt fit well in the arrow. See attached screenshot.
Can you make channels inline with podcasts?
![title_in_arrow copy](https://cloud.githubusercontent.com/assets/11992232/7201470/6e627aee-e4ff-11e4-8a73-992b248452e9.png)

Mac > Chrome/firefox full screen layout

**Comment by natsteinmetz** [comment] 2015-04-19 04:18
Duplicate of #40 .

**Closed by natsteinmetz** 2015-04-19 04:18 UTC
Labels: duplicate
